<?php

/****
	en_language.php 
	Skapad av Patricio Santiago
	Copyright Kortsystem i Gislaved AB
	Version 1.3 - 2016-03-10
****/	 

//	Att göra: #

/*
	Språk > Engelska
	
	$lg_ är prefixen för språk som används på sidorna. Ordet som följer
	är det som är engelska benämning för ordet. Själva språket anges inom
	'' (taggarna).
	
	OBS! Ändra INTE variabel annars slutar sidorna fungera helt.
	Man ska endast ändra det inom '' (taggarna). Exempel:	
	
	$lg_variabel = 'Kan Ändras';
	
	Regler (för snygg formatering):
	- VIKTIG! Taggen ' får man EJ skriva in direkt annars slutar allt att fungera.
	  Är man tvungen att ha med vid exempelvis 'Don't' så skriver man 'Don\'t'.
	  Alltså för att få ut ' skrivs den som \' annars skapar man ett syntax error. 
	- Sätt inga mellanrum före eller efter ordet. Annars kan det se konstigt ut.
	- Sätt inga : (kolon) efter ord, dessa sätts automatiskt. Annars blir det "Pris::"
	- Sätt inga . (punkt/er) efter ord, dessa sätts automatiskt. Exempelvis:
	  'Sök' används vid flera tillfällen, som "Sök..." och i vissa menyer utan punkter.
	  Om man skriver in 'Sök...' som kommer det bli "Sök......" på sökfältet och vissa 
	  menyer blir det "Sök..." där dessa punkter inte ska vara med.
	- Skriv in ordet så rent som det går, inga special förklaringar, parenteser eller
	  andra onödiga tecken/krumellurer.
*/

$lg_language = 'English'; // Aktiva språket
$lg_ = '';

$lg_swedish = 'Swedish';
$lg_english = 'English';

// Meny
$lg_search = 'Search';
$lg_product = 'Products';
$lg_document = 'Document';
$lg_contact = 'Contact';

$lg_cart = 'Cart';
$lg_empty = 'Empty';
$lg_items = 'items';
$lg_order = 'Order';

$lg_home = 'Home';
$lg_menu = 'Menu';
$lg_back = 'Back';

// Foten
$lg_copyright = '&copy; Kortsystem i Gislaved AB';
$lg_cookies = 'Information about cookies';
$lg_contactMessage = '<span>Phone: <b>+46 371-222 444</b></span><i> | </i><span>E-mail: <b>info@kortsystem.se</b></span>';
$lg_cookiesMessage = 'We use cookies for technical reasons only - to improve the user experience at Kortsystem.se. \nCookies are used to remember language settings and measure traffic generated by our website. \nThe collected information is anonymous and does not contain any personal data like name or e-mail. \nCollected information cannot be used for tracking by Kortsystem.';

// Kategori
$lg_next = 'Select product';

// Artikel
$lg_price = 'Price for';
$lg_total = 'Total value';
$lg_discount = 'Quantity discount';
$lg_addCart = 'Add to cart';
$lg_disableCart = 'Get in touch';
$lg_disableCart2 = 'Not available';
$lg_addSample = 'Get a sample';
$lg_disableSample = 'Sample not available';
$lg_removeSample = 'Remove sample';
$lg_textSample = 'A sample with general characteristics.';
$lg_artnr = 'art.no.';
$lg_images = 'Click for bigger size';
$lg_choice = 'Modify your product';
$lg_noChoice = 'This product can not be modified';
$lg_description = 'Product description';

$lg_chooseModel = 'Choose model';
$lg_chooseSize = 'Choose size (L x H)';
$lg_chooseAngle = 'Choose angle';
$lg_chooseAmount = 'Choose amount';

$lg_cartAlert = 'This is not an acceptable number\nOnly whole numbers are allowed';

// Artikel - Produkt specifikt
$lg_noTecken = 'No characters choosen';
$lg_noGSS = 'No serial created';

// Artikel - GSS
$lg_createSerial = 'Create serial for';

$lg_startSerial = 'Begin serial from';
$lg_endSerial = 'and end serial at';

$lg_intervalSerial = 'Serial interval';
$lg_eachSerial = 'Serial';
$lg_otherSerial = 'Two';
$lg_tenthSerial = 'Ten';

$lg_repeatSerial = 'Repeat same serial';

$lg_serialWarningOne = '*This product is sold in sheets. Generated serials will automatically count to the end of a sheet.';
$lg_serialWarningTwo = 'Notice that you need to deselect a box (they turn green) if you want the information and price to update.';

$lg_amountZero = 'Amount of zeros';
$lg_amountMultiplied = 'times';
$lg_selectBackground = 'Choose background colour';

// Dokument
$lg_download = 'Download';
$lg_forDownload = 'for download';

// Sök
$lg_backResult = 'Show previous results';
$lg_moreResult = 'Show more results';
$lg_endResult = 'There is no more results to show';

// Kundvagn
$lg_emptyCart = 'Cart is empty';
$lg_totalCart = 'Total';
$lg_vatCart = 'excl. VAT';
$lg_continueCart = 'Continue shopping';
$lg_orderCart = 'Submit order';

$lg_amountCart = 'Amount of';
$lg_priceCart = 'Price';

$lg_remove = 'Remove';
$lg_restore = 'Restore';

$lg_special_1 = 'Specification for character sheets';
$lg_special_2_yellow = 'Specification for series in <b>yellow</b>';
$lg_special_2_white = 'Specification for series in <b>white</b>';

$lg_messageCart = 'Save changes made and <b>'.$lg_continueCart.'</b> or <b>'.$lg_orderCart.'</b>';

// Felsökning
$lg_error = 'There was an error!'; // Generisk fel
$lg_noProduct = 'The product was not added.'; // Sker när GET koden inte stämmer på kundvagn
$lg_browser = 'Your webbrowser is outdated!\nThe website will NOT display correctly!\nYou need to update to place orders from website.'; // Varning för gammal < IE9

// Nyheter
$lg_news = "News";
$lg_events = "Events";
$lg_oldEvents = "Older";
$lg_newEvents = "Newer";

// Färger
$lg_yellow = 'Yellow';
$lg_white = 'White';

// Siffror
$lg_none = 'None';
$lg_two = 'Two';
$lg_three = 'Three';
$lg_four = 'Four';

?>